Rtx 30 i builder builder
3Hards/RayTracer pull request #17
Opened 2023-04-25 15:19 UTC by badidu09

2023-04-25 19:13 UTC, TTENSHII commented on src/Builder/Builder.cpp
> +}
```suggestion
}

```

2023-04-25 19:13 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +}
```suggestion
}

```

2023-04-25 19:13 UTC, TTENSHII commented on src/Builder/IBuilder.hpp
> +}
```suggestion
}

```

2023-04-25 19:16 UTC, TTENSHII commented on src/Builder/IBuilder.hpp
Knowing that the scenes have already been done, it would be nice to integrate them into this pr.

2023-04-25 19:20 UTC, TTENSHII commented on src/Builder/IBuilder.hpp
> +            virtual void build() = 0;
What is this ?

2023-04-25 19:23 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            ~Builder() = default;
Useless line

2023-04-25 19:26 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            void addPrimitive(libconfig::Setting *setting);
This method has nothing to do here

2023-04-25 19:26 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            void addLight(libconfig::Setting *setting);
This method has nothing to do here

2023-04-25 19:26 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            void addCamera(libconfig::Setting *setting);
This method has nothing to do here

2023-04-25 19:28 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            void buildTransformation() override;
This method is not override

2023-04-25 19:28 UTC, TTENSHII commented on src/Builder/Builder.hpp
> +            void buildTransformable() override;
This method is not override

2023-04-30 19:02 UTC, guillaumeAbel requested changes

2023-04-30 19:02 UTC, guillaumeAbel commented on src/Builder/Builder.cpp
> +// #include "AmbientLight.hpp"
implement ambientLight

2023-04-30 20:17 UTC, TTENSHII commented on Config/test.cfg
> +};
```suggestion
};

```

2023-04-30 20:17 UTC, TTENSHII commented on src/Builder/CMakeLists.txt
> +)
```suggestion
)

```

2023-04-30 20:17 UTC, TTENSHII commented on src/Builder/CMakeLists.txt
> +
```suggestion
```

2023-04-30 20:17 UTC, TTENSHII commented on src/Builder/IBuilder.hpp
> +}
```suggestion
}

```

2023-05-01 10:54 UTC, badidu09 commented on src/Builder/Builder.cpp
> +// #include "AmbientLight.hpp"
added

2023-05-09 19:50 UTC, guillaumeAbel approved these changes

2023-05-09 19:54 UTC, merged