Rtx 32 i scene scene
3Hards/RayTracer pull request #9
Opened 2023-04-23 17:16 UTC by TTENSHII

2023-04-23 18:47 UTC, badidu09 reviewed
Everything's look good

2023-04-24 13:56 UTC, guillaumeAbel requested changes

2023-04-24 13:56 UTC, guillaumeAbel commented on src/Scene/Scene.cpp
> +        _filename(filename),
rm

2023-04-24 13:56 UTC, guillaumeAbel commented on src/Scene/Scene.hpp
> +            std::shared_ptr<Transformable::Camera::ICamera> _camera;
should be lists

2023-04-24 15:27 UTC, guillaumeAbel approved these changes

2023-04-24 15:27 UTC, merged